### PR TITLE
Use /bin/sh instead of bash

### PR DESCRIPTION
**Pull request by AMDmi3**
There's no need to use bash here

### CODE REVIEW

**Comment by denji** [comment]
:+1:

**Comment by denji** [comment]
Rebased denji/fastnetmon@870141fe2952913bc88bc074980953e7d4775c24 #253

**Comment by caquino** [comment]
Just curious but why use /bin/sh instead of /usr/bin/env bash? for example by default ubuntu is symlinking /bin/sh to dash which breaks some scripts.

**Comment by AMDmi3** [comment]
These some scripts should obviously still use bash shebang (though it would be better to fix them to not require bash instead), while ones which do not depend on any bashisms including this one must use /bin/sh to not pull in unneeded bash dependency.

**Comment by denji** [comment]
@caquino You think everyone has bash to each OS? sh is always there

**Pull request closed without merging**
