### PR TITLE
Add support for the "include" directive in /etc/fastnetmon.conf

### PR DESCRIPTION
**Pull request by kaosdrachen**
Quick and dirty hack. Should compile without any issue. 

Only real potential problem is that currently it doesn't check for looping includes.

### CODE REVIEW

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for you code!

I have some ideas right now. glob.h has very huge list of options but I want to restrict it because wildcard is pretty tricky thing.

I want to have support for following cases:
* Include of certain file, i.e. include_file /etc/fastnetmon/fastnetmon_hosts.conf
* Include of all files from some directory in strict order, i.e. include_directory /etc/fastnetmon/fastnetmon_hosts. 

As you can see, all paths are absolute because we do not have "standard" FastNetMon's folder to use it as base for relative paths.

Complicated cases, i.e. "include_file /etc/fastnetmon/conf/1111*.conf" I want to avoid because it's very tricky to handle it.

Also I do not want to work with glob.h because it's too C'ish and looks very bad with C++ code (you know, manual memory allocation and a lot of c_str calls).

We could use Boost directory iterator for this case. Could you port code to it?

I just finished guide about contribution to project https://github.com/pavel-odintsov/fastnetmon/blob/master/docs/DEVELOPER_GUIDES.md and it could be useful for you.

Thank you and sorry about delay! :)

**Comment by pavel-odintsov** [comment]
Also we just merged nice PR about configuration file sanity checks here: https://github.com/pavel-odintsov/fastnetmon/pull/575

**Comment by pavel-odintsov** [comment]
So I have idea how we could implement this approach with includes. 

* Replace reading from ifstream with getline here: https://github.com/pavel-odintsov/fastnetmon/blob/master/src/fastnetmon.cpp#L1020 by reading configuration from vector<std::string>.
* vector<std::string> (list of all string lines from configuration file) could be prepared with function read_file_to_vector
* Then you could execute first iteration over this vector and replace all include_file and include_directory with content of this files.
* Then you could append all data (without include_file and include_folder) calls to target std::vector
* Read all configuration options from std::vector<std::string> instead of readline :)
* Do not forget trim :)

**Comment by kaosdrachen** [comment]
Wow, that was quick. 

I have zero experience with libboost; then again, I had zero experience with glob() until I took a crack at this. That said, looks like 575 already sorts this out.


I really do recommend shifting the config base directory from /etc/ to /etc/fastnetmon/ because even without the added include directives there's already fastnetmon.conf, networks_list and networks_whitelist, which is two more files from a single package than is prudent -- and the latter two names are somewhat generic, making it highly nonobvious which piece of software they actually belong to. 

Cleaning up the config directory structure in general is the next thing I was planning to tackle, anyway. :)

Basic layout:

/etc/fastnetmon/ <-- new config-root directory
$config_root/fastnetmon.conf <-- base config file.
$config_root/networks_list,  $config_root/networks_whitelist <-- default locations for both
$config_root/conf.d/ <-- empty directory, created by install program; default fastnetmon.conf includes every file in this directory.

**Comment by pavel-odintsov** [comment]
Great idea about custom folder for fastnetmon. We could schedule it for next release.

**Comment by pavel-odintsov** [comment]
Closed now. Feel free to open after applying changes. Thank you!

**Pull request closed without merging**
