### PR TITLE
fix redis log

### PR DESCRIPTION
**Pull request by damiankam**
I think this is fix because `#ifdef MONGO` was blocked by `#ifdef REDIS`.

### CODE REVIEW

**Comment by pavel-odintsov** [comment]
Great job! Thank you!

**Comment by pavel-odintsov** [comment]
Please specify you full name and email address I need it for contributor list.

**Comment by damiankam** [comment]
Dima Kaminsky
demon.kaminsky@gmail.com

**Comment by pavel-odintsov** [comment]
Thanks!

**Pull request merged**
